{
    "name": "HR Recruitment Custom",
"depends": [
    "base",
    "base_automation",
    "mail",
    "hr",
    "hr_recruitment",
    "grc_backbone"
],
    "application": False,
    "installable": True,
    "auto_install": False,
    "data": [
        "models/00_models.xml",
        "models/01_fields.xml",
        "models/02_interview_relations.xml",
        "models/03_recruitment_document.xml",
        "models/04_board_decision_bridge_fields.xml",
        "models/04_required_document_checklist.xml",
        "models/05_required_document_submission.xml",
        "models/06_required_document_submission_request.xml",
        "models/07_applicant_declaration.xml",
        "security/ir.model.access.csv",
        "data/01_role_definition_automation.xml",
        "data/02_tor_selection_values.xml",
        "data/03_tor_normalization_automation.xml",
        "report/01_paperformat.xml",
        "report/02_tor_report_templates.xml",
        "report/03_tor_report_actions.xml",
        "data/04_tor_workflow_actions.xml",
        "data/05_interview_selection_values.xml",
        "data/06_mcep_interview_questions.xml",
        "data/07_interview_automation.xml",
        "data/08_interview_workflow_actions.xml",
        "report/04_interview_report_templates.xml",
        "report/05_interview_report_actions.xml",
        "report/06_required_document_checklist_report_templates.xml",
        "report/07_required_document_checklist_report_actions.xml",
        "report/08_legal_document_validity_declaration_report_templates.xml",
        "report/09_legal_document_validity_declaration_report_actions.xml",
        "data/09_interview_document_workflow_actions.xml",
        "data/10_required_document_types.xml",
        "data/11_required_document_checklist_actions.xml",
        "data/12_required_document_checklist_pdf_actions.xml",
        "data/13_required_document_submission_identity_actions.xml",
        "data/14_required_document_submission_cleanup_actions.xml",
        "data/15_required_document_submission_review_actions.xml",
        "data/16_required_document_submission_request_actions.xml",
        "data/17_required_document_writeback_safety_actions.xml",
        "data/18_declaration_actions.xml",
        "data/19_evaluation_gate_actions.xml",
        "data/20_board_decision_actions.xml",
        "views/01_recruitment_views.xml",
        "views/02_recruitment_document_views.xml",
        "views/03_required_document_checklist_views.xml",
        "views/04_required_document_submission_views.xml",
        "views/05_required_document_submission_request_views.xml",
        "views/06_applicant_declaration_views.xml",
    ],
}
