{
    "name": "Recruitment Governance",
    "summary": "Recruitment-domain governance bridge for Marsellia",
    "depends": [
        "base",
        "hr",
        "hr_recruitment",
        "hr_pool",
        "grc_backbone",
        "mail",
        "documents",
        "sign"
    ],
    "category": "Human Resources",
    "application": True,
    "data": [
        "security/groups.xml",
        "models/01_models.xml",
        "models/02_fields_templates_inverse.xml",
        "models/02_fields_templates.xml",
        "models/03_fields_bridge.xml",
        "models/04_models_runtime.xml",
        "models/05_fields_runtime.xml",
        "models/06_models_runtime_negotiation.xml",
        "models/07_fields_runtime_negotiation.xml",
        "data/01_selection_values.xml",
        "data/02_sequence.xml",
        "data/03_seed_templates.xml",
        "data/04_selection_runtime_negotiation.xml",
        "report/01_paperformat.xml",
        "report/02_hr_job_tor_report_templates.xml",
        "report/03_hr_job_tor_report_actions.xml",
        "report/04_hr_interview_evaluation_report_templates.xml",
        "report/05_hr_interview_evaluation_report_actions.xml",
        "report/06_hr_role_composition_report_templates.xml",
        "report/07_hr_role_composition_report_actions.xml",
        "report/08_hr_declaration_envelope_report_templates.xml",
        "report/09_hr_declaration_envelope_report_actions.xml",
        "actions/01_actions.xml",
        "actions/02_runtime_negotiation_actions.xml",
        "views/01_templates_views.xml",
        "views/02_bridge_views.xml",
        "views/03_runtime_views.xml",
        "views/04_runtime_negotiation_views.xml",
        "menus/01_menus.xml",
        "menus/02_runtime_menus.xml",
        "menus/03_runtime_negotiation_menus.xml",
        "security/ir.model.access.csv"
    ]
}
