{
    "name": 'MCEP HR Employment Custom',
    "summary": 'Marsellia employee lifecycle extensions for native HR employees',
    "category": 'Human Resources',
    "depends": ['base', 'mail', 'hr', 'sign', 'base_automation', 'grc_backbone', 'hr_work_entry', 'hr_holidays'],
    "application": False,
    "installable": True,
    "auto_install": False,
    "data": ['models/01_employee_identification.xml',
 'models/02_employee_declaration.xml',
 'models/03_employee_custody.xml',
 'models/04_employee_training.xml',
 'models/05_employee_permission.xml',
 'models/06_employee_leave.xml',
 'models/07_employee_work_assignment.xml',
 'security/ir.model.access.csv',
 'data/01_employee_identification_automation.xml',
 'data/02_employee_identification_actions.xml',
 'data/03_employee_declaration_automation.xml',
 'data/04_employee_declaration_generate_actions.xml',
 'data/05_employee_declaration_sign_actions.xml',
 'data/06_employee_declaration_artifact_actions.xml',
 'data/07_employee_custody_automation.xml',
 'data/08_employee_custody_type_data.xml',
 'data/09_employee_custody_generate_actions.xml',
 'data/10_employee_custody_sign_actions.xml',
 'data/11_employee_custody_lifecycle_actions.xml',
 'data/12_employee_training_automation.xml',
 'data/13_employee_training_generate_actions.xml',
 'data/14_employee_training_sign_actions.xml',
 'data/15_employee_permission_type_data.xml',
 'data/16_employee_permission_automation.xml',
 'data/17_employee_permission_generate_actions.xml',
 'data/18_employee_permission_sign_actions.xml',
 'data/19_employee_leave_policy_data.xml',
 'data/20_employee_leave_automation.xml',
 'data/21_employee_leave_generate_actions.xml',
 'data/22_employee_leave_sign_actions.xml',
 'data/23_employee_work_assignment_automation.xml',
 'views/01_employee_identification_views.xml',
 'views/02_employee_declaration_views.xml',
 'views/03_employee_custody_views.xml',
 'views/04_employee_training_views.xml',
 'views/05_employee_permission_views.xml',
 'views/06_employee_leave_views.xml',
 'views/07_employee_work_assignment_views.xml',
 'report/01_employee_declaration_paperformat.xml',
 'report/02_common_employee_report_assets.xml',
 'report/03_employee_declaration_f0010_templates.xml',
 'report/05_employee_declaration_f0013_templates.xml',
 'report/06_employee_declaration_f0021_templates.xml',
 'report/07_employee_declaration_f0022_templates.xml',
 'report/08_employee_custody_f0011_templates.xml',
 'report/04_employee_declaration_report_actions.xml',
 'report/09_employee_custody_report_actions.xml',
 'report/10_employee_training_f0008_templates.xml',
 'report/11_employee_training_report_actions.xml',
 'report/12_employee_permission_templates.xml',
 'report/13_employee_permission_report_actions.xml',
 'report/14_employee_leave_templates.xml',
 'report/15_employee_leave_report_actions.xml'],
}
