{
    "name": "GRC Backbone",
    "depends": [
        "base",
        "base_automation",        
        "uom"
    ],
    "installable": True,
    "auto_install": False,
    "data": [
        "security/groups.xml",
        "models/01_models.xml",
        "models/02_fields_core_base.xml",
        "models/03_fields_core_o2m.xml",
        "models/04_fields_task_templates_base.xml",
        "models/05_fields_task_templates_o2m.xml",
        "models/06_location_taxonomy.xml",
        "models/07_decision_template_models.xml",
        "models/08_decision_template_fields.xml",
        "models/09_decision_profile_models.xml",
        "models/10_decision_profile_fields.xml",
        "models/11_decision_reference_variable_models.xml",
        "models/12_decision_reference_variable_fields.xml",
        "models/13_governance_library_models.xml",
        "models/14_governance_library_fields.xml",
        "data/01_selection_values.xml",
        "data/02_sequences.xml",
        "data/03_seed_functional_taxonomy.xml",
        "data/04_seed_task_templates.xml",
        "data/05_seed_libya_regions_districts.xml",
        "data/06_seed_libya_municipalities.xml",
        "data/07_seed_libya_localities.xml",
        "data/08_location_hierarchy_automation.xml",
        "data/09_decision_profile_seed.xml",
        "actions/01_actions.xml",
        "actions/02_actions_task_templates.xml",
        "actions/03_location_actions.xml",
        "actions/04_decision_template_actions.xml",
        "actions/05_decision_profile_actions.xml",
        "actions/06_decision_reference_variable_actions.xml",
        "actions/07_governance_library_actions.xml",
        "actions/08_decision_template_refresh_actions.xml",
        "actions/09_governance_source_refresh_actions.xml",
        "views/01_governance_views.xml",
        "views/02_taxonomy_views.xml",
        "views/03_risk_compliance_views.xml",
        "views/04_commercial_views.xml",
        "views/05_task_templates_views.xml",
        "views/06_location_taxonomy_views.xml",
        "views/07_decision_template_views.xml",
        "views/08_decision_profile_views.xml",
        "views/09_decision_reference_variable_views.xml",
        "views/10_governance_library_views.xml",
        "data/10_decision_engine_cleanup.xml",
        "security/ir.model.access.csv"
    ]
}
